title: Kevin Tran # your name (or website title) here
logo: "" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Science Student studying at Monash University. I hope you enjoy exploring a couple of my projects 
<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbFdYPcObOBMR7SEQIKxn6J7wQ6oR6kgBa-g&usqp=CAU" style="height: 20px; width: 20px;"/> 
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/kevin-tran-974564192/</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here



