title: Kevin Tran 
logo: "images/profile_image.jpeg?raw=true"
description: > 
  Hi There! My names Kevin and I'm a data science graduate from Australia. I am driven by a profound curiosity and have a passion to transform whatever dataset I can find into a compelling narrative. 
  I hope you enjoy exploring a couple of my data science projects :)!
  <br><br>
  <a href="https://www.linkedin.com/in/kevin-tran-974564192/">View My LinkedIn Profile</a>
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

google_analytics: UA-000000-0 

include:
  - override.css


