title: Kevin Tran 
logo: "https://github.com/kevtr0801/kevtr0801.github.io/blob/master/images/profile_image.jpg"
description: > 
  Hi There. My names Kevin and I'm currently studying my masters in data science at Monash University, Australia. I am driven by a profound curiosity and a keen analytical mindset and have a passion to transform whatever dataset I can find into a compelling narrative. 
  So I hope you enjoy exploring a couple of my data science projects :)!
  <br><br>
  <a href="https://www.linkedin.com/in/kevin-tran-974564192/">View My LinkedIn Profile</a>
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

google_analytics: UA-000000-0 

include:
  - override.css


