title: Kevin Tran 
logo: "images/51034EFF-F898-4FE1-B3F9-E44DF05A9581_1_105_c.jpeg?raw=true"
description: > 
  Hi There. My names Kevin and I'm currently studying my masters in data science at Monash University, Australia. I am driven by a profound curiosity and a keen analytical mindset and have a passion to transform whatever dataset I can find into a compelling narrative. 
  So I hope you enjoy exploring a couple of my data science projects :)!
  <br><br>
  <a href="https://www.linkedin.com/in/kevin-tran-974564192/">View my LinkedIn Profile</a>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

