title: Kevin Tran 
logo: "images/20220308_1745440.jpeg?raw=true"
description: > 
  Student currently studying a Masters in Data Science at Monash University, Australia. I am driven by a profound curiosity and a keen analytical mindset, aiming to transform complex datasets into compelling narratives.
  I hope you enjoy exploring a couple of my data science projects :)
  <br><br>
  <a href="https://www.linkedin.com/in/kevin-tran-974564192/> View my Linkedin Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

